joint_limits:
  joint1:
    min_position: 0
    max_positiom: 0
    max_effort: 0
    max_velocity: 0
  joint2:
    min_position: 0
    max_positiom: 0
    max_effort: 0
    max_velocity: 0
  joint3:
    min_position: 0
    max_positiom: 0
    max_effort: 0
    max_velocity: 0
  joint4_1:
    min_position: 0
    max_positiom: 0
    max_effort: 0
    max_velocity: 0
  joint4_2:
    min_position: 0
    max_positiom: 0
    max_effort: 0
    max_velocity: 0
---
link_mass:
  base_link:
    mass: 25.653991698128898
  flange_link:
    mass: 0.038742319690396002
  link1:
    mass: 5.9266086500812403
  link2:
    mass: 44.045181635512797
  link3:
    mass: 37.982216868815698
  link4_1:
    mass: 1.2539577357262599
  link4_2:
    mass: 2.8041529195513002