set(_AMENT_PACKAGE_NAME "urdf_expansion")
set(urdf_expansion_VERSION "0.0.0")
set(urdf_expansion_MAINTAINER "eliseev <v.eliseev@rtc.ru>")
set(urdf_expansion_BUILD_DEPENDS "urdf" "urdfdom_headers" "urdfdom")
set(urdf_expansion_BUILDTOOL_DEPENDS "ament_cmake")
set(urdf_expansion_BUILD_EXPORT_DEPENDS "urdf" "urdfdom_headers" "urdfdom")
set(urdf_expansion_BUILDTOOL_EXPORT_DEPENDS )
set(urdf_expansion_EXEC_DEPENDS "rclcpp" "urdf" "urdfdom_headers" "urdfdom")
set(urdf_expansion_TEST_DEPENDS )
set(urdf_expansion_GROUP_DEPENDS )
set(urdf_expansion_MEMBER_OF_GROUPS )
set(urdf_expansion_DEPRECATED "")
set(urdf_expansion_EXPORT_TAGS)
list(APPEND urdf_expansion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
