joint_limits:
  joint1:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint2:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint3:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint4:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint5:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint6:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0
  joint7:
    min_position: 0
    max_position: 0
    max_effort: 0
    max_velocity: 0