name: Humble Source Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  humble_source:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
              
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions && source /opt/ros/humble/setup.bash

      - name: Build the workspace
        run: . /opt/ros/humble/setup.sh && colcon build --event-handlers console_cohesion+

      - name: Test the workspace
        run: . install/setup.bash && colcon test --event-handlers console_cohesion+