name: Build and test
on:  
  workflow_dispatch:
    push:
      branches:
        - [ "main"]
    pull_request:
      branches:
        - [ "main"]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: humble
      ros_version: 2
    steps:
      - run: sudo apt install libgtest-dev
      - uses: actions/checkout@v4
      - name: Update, build, and test
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y python3-pip
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --event-handler console_direct+
          colcon test --event-handler console_direct+